### ISSUE TITLE
Unable to open '': Cannot read property 'map' of undefined.

### ISSUE THREAD

**Issue by Artfloriani** [HookyQR/VSCodeGitHubIssues#7] opened 2016-03-16 14:22 UTC
I get this error when I try to click on the issues icon, on the bottom left corner. 

Do I have to do any setup in order to have this running?

**Comment by HookyQR** [comment] 2016-03-17 06:55
Shouldn't do. Can you provide the repo url please. The problem should automatically replicate at my end.

**Comment by Artfloriani** [comment] 2016-03-17 16:43
It is a private repo. I have my credentials saved on my git config. Is there any way to import issues from private?

**Comment by HookyQR** [comment] 2016-03-17 17:05
Hmm, to be honest, I haven't tried. I don't have a paid github account, so I can't test it. It may just be an issue with the URL structure but I don't see any reference to it being different.

For authorised access you do can to use your authToken which you can provide in your settings file as:

```
 "GitHubIssues.authToken": "12344ABCDE"
```

I use this to enable more requests on the API, but I'm taking a guess that setting this correctly may solve the problem.

**Comment by Artfloriani** [comment] 2016-03-17 17:42
I use an educational account which enables to have private repos. The authToken removed that error but now I don't see anything when I click on the issues tab. It might also be an issue that I'm a collaborator on a repo that I`m not the owner. 

Thanks for the support.

**Comment by HookyQR** [comment] 2016-03-17 18:44
That shouldn't cause any problems. I'm assuming there are issues in the repo when you're looking at it in the browser.

Is the status bar showing any issues? (Does one of the icons have a number next to it?)

**Comment by Artfloriani** [comment] 2016-03-17 18:51
There are issues in the repo. I use them a lot and that is why I wanted to integrate with VSCode. 

On VS Code there is no number next to it.

**Comment by HookyQR** [comment] 2016-03-17 19:48
Thanks for the update. Try the following:

Click **Help->Toggle Developer Tools** then select the **Resources** tab and **Local Storage->file://** then you'll have to find the line that has **storage://workspace/_{pathToLocalWorkspace}_/hookyqr.gihubissues** and delete that line.

Reload the workspace and let me know if that has fixed the issue. Fingers crossed.

**Comment by Artfloriani** [comment] 2016-03-17 19:57
Thanks for your help!

Ok, so now I still don`t see anything when I click the Issues Icon but if I check the Local Storage again I can see the issues inside the **storage://workspace/{pathToLocalWorkspace}/hookyqr.gihubissues** entry.

**Comment by Artfloriani** [comment] 2016-03-17 20:06
I created a private repo and invited you in case you want to test it ;)

**Comment by HookyQR** [comment] 2016-03-18 04:56
Thanks @Artfloriani. I should be able to take a look this weekend.

**Comment by HookyQR** [comment] 2016-03-20 09:51
It seems the default settings were not working in your favour. I've changed it from only showing `bug`, and `Unlabelled` to showing all issues. This has brought in a new tag of `*` which can be used for **_'all other labels'**_.

Published as v0.1.0.

This doesn't address the issue caused by initially opening a private repo without an API token set. I'll probably add a `reset Git Hub Issues` function which should take care of that.

Thanks again for your help @Artfloriani.

**Comment by Artfloriani** [comment] 2016-03-20 10:16
Thank you @HookyQR. It is now working :) 

Please, tell me when you're done with the private repo so that I can delete it.

**Comment by HookyQR** [comment] 2016-03-20 17:45
All don @Artfloriani. You can close it now.

**Closed as completed by HookyQR** 2016-03-20 17:45 UTC
Labels: bug

**Comment by wembernard** [comment] 2016-07-12 09:21
Bug is still here. Should catch the exception and handle it with some documentation such as "Provide some authToken in your settings.json".

Workaround is working though. Thanks.

**Comment by wimhaanstra** [comment] 2016-11-18 05:56
I am also having this exact problem. Tried removing the local storage, but the same issue pops up again. I have `GitHubIssues.authToken` in my user settings.json.

Maybe the difference is, that this is a repository in an organization? The url is in this format:

`
https://<username>@github.com/<organization_name>/<repo_name>.git
`

**Comment by HookyQR** [comment] 2016-11-18 07:32
Sorry folks, I've kind of dropped the ball on this extension. May be able to get some work done on it in the next week or so.
